#!/usr/bin/env bash

# uninstalls all packages not found in the files give on the command line
# this is super hacky but works

(( $(id -u) != 0 )) && { echo "root required" ; exit 1 ; }
[[ -z "$*" ]] && { echo "no files given" ; exit 2 ; }
for input in "$@" ; do [[ -f "$input" ]] || { echo "invalid file: $input" ; exit 2 ; } ; done
pacman -D --asdeps $(comm -13 <(cat "$@" <(pacman -Qgq base{,-devel}) | sort) <(pacman -Qqe | sort)) && ./pacman-remove-orphans
