#!/usr/bin/env bash

# reads packages from stdin and outputs a list of all their dependencies

tmpfile="$(mktemp)"
while read package ; do
    pactree -l $package | cut -d ' ' -f 1 >> "$tmpfile"
done
sort "$tmpfile" | uniq
